-- =====================================================================
-- Tracking numbers are now "<SLIN code>-<5-digit counter>" (e.g.
-- 6200AE-00001), issued once, at a travel request's FIRST Supervisor
-- approval, and reused for that trip's expense report. The counter is a
-- single sequence so numbers are unique and count up in approval order.
-- Generated by the database (not the browser) so two approvals at the same
-- moment can never receive the same number.
--
-- Existing rows keep whatever tracking_number they already have.
-- =====================================================================

create sequence if not exists public.travel_tracking_seq start 1 minvalue 1;

create or replace function public.assign_tracking_number(p_slin_id uuid)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_code text;
  v_n bigint;
begin
  select slin_code into v_code from public.slins where slin_id = p_slin_id;
  if v_code is null then
    raise exception 'Unknown SLIN %', p_slin_id;
  end if;
  v_n := nextval('public.travel_tracking_seq');
  return v_code || '-' || case when v_n > 99999 then v_n::text else lpad(v_n::text, 5, '0') end;
end;
$$;

revoke all on function public.assign_tracking_number(uuid) from public;
grant execute on function public.assign_tracking_number(uuid) to authenticated;
